modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/TartaricAcid/TouhouLittleMaid/issues"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    # updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL = "https://discord.gg/re4xQtb"
    logoFile = "logo.png"
    credits = "Verclene, ZUN"
    authors = "${mod_authors}"
    description = '''${mod_description}'''

[[mixins]]
    config = "${mod_id}.mixins.json"

[[accessTransformers]]
    file = "META-INF/accesstransformer.cfg"

[modproperties.touhou_little_maid]
    catalogueItemIcon = "touhou_little_maid:hakurei_gohei"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"